In [1]:
import tensorflow as tf
import datetime

In [2]:
print(f"The notebook last run time:{datetime.datetime.now()}")

The notebook last run time:2023-10-19 12:37:35.331316


In [3]:
print(tf.__version__)

2.13.0


In [4]:
#Create a scalar
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
#create a vector (more than 0 dimensions)
vector=tf.constant([10,10])
matrix=tf.constant([[10,7],[7,10]])
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with 'dtype'
print(vector)
print(matrix)
print(another_matrix)

tf.Tensor([10 10], shape=(2,), dtype=int32)
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)


In [7]:
print(vector.ndim)
print(matrix.ndim)
print(another_matrix.ndim)

1
2
2


In [8]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [9]:
tensor.ndim

3

Tensorflow can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

224, 224 (the first 2 dimensions) are the height and width of the images in pixels.

3 is the number of colour channels of the image (red, green blue).

32 is the batch size (the number of images a neural network sees at any one time).


In [10]:
#scalar: a single number.
#vector: a number with direction (e.g. wind speed with direction).
#matrix: a 2-dimensional array of numbers.
#tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

In [11]:
#Creating Tensors with tf.Variable()
#The difference between tf.Variable() and tf.constant() is tensors created with tf.constant can't be changed, tf.Variable() are mutable (can be changed)
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [12]:
#to change a element of a tf.Variable() tensor requires the assign() method.
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [13]:
#Whic one should you use? tf.constant() or tf.Variable()?
#It will depend on what your problem requires. Howewer,most of time, Tensorflow will automatically choose for you (when loading data or modelling data)

In [14]:
# Create two random (but the same) tensors
random1=tf.random.Generator.from_seed(42) #set the seed for reproducibility
random1=random1.normal(shape=(3,2)) # create tensor from a normal distrubition
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))

#are the equal
random1,random2,random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
random3=tf.random.Generator.from_seed(42)
random3=random3.normal(shape=(3,2))
random4=tf.random.Generator.from_seed(11)
random4=random4.normal(shape=(4,3))

random3, random4, random1 == random3, random3 == random4


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638, -0.3652325 ],
        [ 0.61883307, -1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967,  0.37944323],
        [-0.6664026 ,  0.6054596 ,  0.19181173]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)

In [16]:
#Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
#Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [17]:
#Shuffle in the same order every time using the seed parameter (won't actually be the same)
#seed=42 sets the gloabal seed,therefore usually we accept 42 
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [18]:
#Other ways to make tensors

#Make a tensor of all ones
print(tf.ones(shape=(3,2)))
#Make a tensor of all zeros
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [19]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) #create a numpy array between 1 and 25
A=tf.constant(numpy_A,shape=[2,3,4]) # note:the shape total (2*4*3) has to match the number of elements in the array
numpy_A,A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

In [20]:
#Getting information from tensors (shape,rank,size)

#Shape:the length(number of elements) of each dimensions of a tensor
#Rank:The number of tensor dimensions.
#Axis or Dimension:A particular dimension of a tensor
#Size:The total number of items in the tensor


#Create a 4 tensor (4 dimensions)
rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [22]:
#Get various attributes of tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along axis 0 of tensor:",rank_4_tensor.shape[0])
print("Elements along axis of tensor:",rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):",tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [23]:
# Get the first 2 items of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor=tf.constant([[10,7],[3,4]])

#Get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [26]:
#You can also add dimensions to your tensor whlist keeping the same information
#present using tf.newaxis

#Add an extra dimension (to the end)
rank_3_tensor=rank_2_tensor[...,tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor,rank_3_tensor



(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

In [27]:
tf.expand_dims(rank_2_tensor,axis=-1) #-1 means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [29]:
#Manipulating tensors (tensor operations)

tensor=tf.constant([[10,7],[3,4]])
print(tensor+10)
print(tensor*10)
print(tensor-10)


tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -3]
 [-7 -6]], shape=(2, 2), dtype=int32)


In [30]:
#Matrix Mutliplication 
"""One of the most common operations in machine learning algorithms"""
"""Tensorflow implements this matrix multiplication functionality in the tf.matmul() method"""

tf.matmul(tensor,tensor)




<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [31]:
#Matrix multiplication with pytohn operator @
tensor @tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [32]:
X=tf.constant([[1,2,],[3,4],[5,6]])
Y=tf.constant([[7,8],[9,10],[11,12]])

In [33]:
#Try to matrix multiply them (will error)
X@Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).
Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).
We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.
tf.transpose() - switches the dimensions of a given tensor.

In [34]:
#Let's try tf.reshape() first.
tf.reshape(Y,shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [35]:
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [36]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [37]:
#The dot product
#Multiplying matrices by eachother is also referred to as the dot product
#You can perform th tf.matmul() operating using tf.tensordot()

print(tf.tensordot(tf.transpose(X),Y,axes=1))

#Perform matrix multiplication between X and Y (transposed)
print(tf.matmul(X,tf.transpose(Y)))

#perform matrix multiplication between X and Y (reshaped)

print(tf.matmul(X,tf.reshape(Y,(2,3))))

# Hmm... they result in different values.

# Which is strange because when dealing with Y (a (3x2) matrix), 
# reshaping to (2, 3) and tranposing it result in the same shape.




tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


In [38]:
#Check shapes of Y,reshaped Y and transposed Y
Y.shape,tf.reshape(Y,(2,3)).shape,tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [39]:
#But calling tf.reshape() andd tf.transpose() on Y don't necessarily result
#in the same values.

#Check values of Y,reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y,(2,3)),"\n")

print("Y transposed:")
print(tf.transpose(Y))



Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


As you can see, the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:

tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.
So which should you use?

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

In [41]:
#Getting the absolute value
D=tf.constant([-7,-10])
print(D)
#Get the abs value
tf.abs(D)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [42]:
#Finding the min,max,mean,sum (aggregation)
F=tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.57263519, 0.43896737, 0.31730099, 0.6398789 , 0.6507075 ,
       0.05721497, 0.86091298, 0.66030555, 0.30829542, 0.47417844,
       0.4302438 , 0.25976489, 0.18194758, 0.62179753, 0.05249723,
       0.64756013, 0.33445436, 0.48181668, 0.10843574, 0.20367436,
       0.87432102, 0.10809801, 0.54823377, 0.65589916, 0.53259957,
       0.98470701, 0.05416267, 0.43442251, 0.24062216, 0.49562388,
       0.3453104 , 0.37212977, 0.33964271, 0.96844555, 0.49730183,
       0.86866144, 0.54158128, 0.17948584, 0.04030193, 0.06385534,
       0.42109349, 0.49411695, 0.27470884, 0.46729256, 0.58692958,
       0.15959756, 0.99441744, 0.69813862, 0.59128199, 0.11441348])>

In [43]:
#Find the maximum element position of F
print(tf.argmax(F))
# Find the minimum element position of F
print(tf.argmin(F))



tf.Tensor(46, shape=(), dtype=int64)
tf.Tensor(38, shape=(), dtype=int64)


In [44]:
#Sequeezing a tensor(removing all single dimensions)

#Create a rank 5(5 dimensions) tensor of 50 numbers between 0 and 100
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G.shape,G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [47]:
#Sequeeze tensor G (remove all 1 dimensions)
G_squeezed=tf.squeeze(G)
G_squeezed.shape,G_squeezed.ndim

(TensorShape([50]), 1)

In [49]:
#One-hot encoding
some_list=[0,1,2,3]

#One hot encode them 
tf.one_hot(some_list,depth=4)

#Specify custom values for on and off encoding
tf.one_hot(some_list,depth=4,on_value="We're live!",off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

In [52]:
H=tf.constant(np.arange(1,10))
print(tf.square(H))


tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)


In [53]:
#Manipulating tf.Variable tensors

#Create a variable tensor
I=tf.Variable(np.arange(0,5))

#Assign the final value a new value of 50
I.assign([0,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [54]:
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [55]:
#Tensors and Numpy

#Create a tensor from Numpy array
J=tf.constant(np.array([3.,7.,10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [56]:
#Convert tensor J to Numpy with np.array()
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [57]:
#Convert tensor J to NumPy with .numpy()
J.numpy(),type(J.numpy()) 

(array([ 3.,  7., 10.]), numpy.ndarray)

In [58]:

# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [60]:
#In your TensorFlow adventures, you might come across
#Python functions which have the decorator @tf.function.

#Create a simple function

def func(x,y):
    return x**2+y
x=tf.constant(np.arange(0,10))
y=tf.constant(np.arange(10,20))
func(x,y)


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [62]:
#Create the same function and decorate it with tf.function

@tf.function
def tf_function(x,y):
    return x**2+y
tf_function(x,y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>